### ISSUE TITLE
Expose NavUtilities variables for RasterPropMonitor

### ISSUE THREAD

**Issue by MOARdV** [kujuman/NavInstruments#4]
I have a request on the RPM GitHub page to expose variables from NavUtilities to allow for custom HUD and MFD setups.  However, since this mod already has RPM integration, I think it would make more sense to expand the RPM integration to expose those variables.  Depending on the development status of this mod, I can provide information for how to do so, or I can provide a pull request with the appropriate changes.

**Comment by kujuman** [comment]
Sorry, just seeing this now, with 1.1. If this is still something that you think should happen, let me know and I'll take a look at exposing variables. (I might need assistance with this, and I want to get NavUtils in 1.1 before I work more on features)

**Comment by kujuman** [comment]
Okay, I've gone ahead and exposed several variables, based upon requests in my own thread.
